"use client";
// lib/storage/upload-delivery-order.ts
//
// Client-side resumable upload helper for Delivery Order documents.
// Mirrors lib/storage/upload-photo.ts but uses uploadBytesResumable so
// the form can render a progress bar — DO files (multi-page PDFs) can
// be 5-10MB whereas inventory photos are sub-MB after compression.
//
// Storage path: delivery-orders/{doId}/document.{pdf|jpg|png} — matches
// the storage.rules allowlist. doId is generated by the form BEFORE
// calling this helper so the Firestore record and the file share an id.

import {
  ref,
  uploadBytesResumable,
  getDownloadURL,
} from "firebase/storage";

import { storage } from "@/lib/firebase/client";

const ALLOWED: Record<string, "pdf" | "jpg" | "png"> = {
  "application/pdf": "pdf",
  "image/jpeg": "jpg",
  "image/png": "png",
};

export type DoUploadProgress = {
  bytesTransferred: number;
  totalBytes: number;
};

export type DoUploadResult = {
  url: string;
  contentType: "application/pdf" | "image/jpeg" | "image/png";
  path: string;
};

export async function uploadDeliveryOrderDocument(
  doId: string,
  file: File,
  onProgress?: (p: DoUploadProgress) => void,
): Promise<DoUploadResult> {
  const ext = ALLOWED[file.type];
  if (!ext) throw new Error("Unsupported file type. Use PDF, JPG, or PNG.");
  if (file.size >= 10 * 1024 * 1024) throw new Error("File exceeds 10MB.");

  const path = `delivery-orders/${doId}/document.${ext}`;
  const storageRef = ref(storage, path);
  const task = uploadBytesResumable(storageRef, file, { contentType: file.type });

  // uploadBytesResumable returns an UploadTask, not a Promise — wrap it so
  // the caller can `await` and so we can fire the progress callback.
  return new Promise<DoUploadResult>((resolve, reject) => {
    task.on(
      "state_changed",
      (snap) => {
        onProgress?.({
          bytesTransferred: snap.bytesTransferred,
          totalBytes: snap.totalBytes,
        });
      },
      reject,
      async () => {
        try {
          const url = await getDownloadURL(task.snapshot.ref);
          resolve({
            url,
            contentType: file.type as DoUploadResult["contentType"],
            path,
          });
        } catch (err) {
          reject(err);
        }
      },
    );
  });
}
