// quick-kayinleong-007 — Location-update Server Action.
//
// Staff can scan an individual item barcode (SKU or externalBarcode) or a
// group barcode (checkoutGroups doc ID) and update the location field on
// all affected inventory documents in a single writeBatch.
//
// Barcode resolution order (per research Pitfall 4):
//   1. adminDb.collection("inventory").doc(barcodeValue).get()
//      — O(1) direct read; SKU === doc ID per PROJECT.md key decision #14.
//   2. adminDb.collection("inventory").where("externalBarcode", "==", barcodeValue)
//      — covers third-party barcodes printed on product packaging.
//   3. adminDb.collection("checkoutGroups").doc(barcodeValue).get()
//      — covers group barcodes generated by quick-kayinleong-006.
//   4. No match → { ok: false, error: "Barcode not recognised." }
//
// Threat-model mitigations (T-007-01 / T-007-02):
//   - requireSession() at entry → unauthenticated calls throw before any read.
//   - Zod schema validates barcodeValue (non-empty) and location (max 100 chars)
//     before any Firestore write.
//
// quick-kayinleong-012 — each update also writes a `location` transaction per
// affected item in the SAME write batch (atomic with the inventory update).
// Group-barcode resolutions stamp eventId/eventName and the owning
// deliveryOrderId so the move surfaces in Item, Event, and DO history; item
// barcodes leave those null (Item history only).

"use server";

import { requireSession } from "@/lib/auth/dal";
import { adminDb } from "@/lib/firebase/admin";
import { FieldValue } from "firebase-admin/firestore";
import { revalidatePath } from "next/cache";
import { z } from "zod";

const UpdateItemsLocationSchema = z.object({
  barcodeValue: z.string().min(1),
  location: z.string().max(100),
});

export type UpdateItemsLocationResult =
  | { ok: true; updatedItemIds: string[]; resolvedAs: "item" | "group" }
  | { ok: false; error: string };

// quick-kayinleong-014 — `qty` carries the group line quantity so the Location
// preview can show how many physical units a group barcode covers (location is
// stored per-SKU, but the user thinks in units). Individual-item scans use 1.
export type ResolveLocationBarcodeItem = { id: string; name: string; sku: string; qty: number };
export type ResolveLocationBarcodeResult =
  | { ok: true; resolvedAs: "item" | "group"; items: ResolveLocationBarcodeItem[] }
  | { ok: false };

export async function updateItemsLocationAction(
  input: unknown,
): Promise<UpdateItemsLocationResult> {
  const session = await requireSession();
  const parsed = UpdateItemsLocationSchema.safeParse(input);
  if (!parsed.success) {
    return { ok: false, error: "Invalid input." };
  }
  const { barcodeValue, location } = parsed.data;

  // quick-kayinleong-012 — every location change writes a `location`
  // transaction alongside the inventory update (same batch → atomic, matching
  // the app's audit-log invariant). qty is 0; location moves have no quantity.
  const txNote = location ? `Location set to "${location}"` : "Location cleared";
  function locationTxFields() {
    return {
      type: "location" as const,
      qty: 0,
      actorUid: session.uid,
      actorName: session.displayName,
      actorRoleAtTimeOfAction: session.role,
      at: FieldValue.serverTimestamp(),
      notes: txNote,
      parentTxId: null,
      clientTxId: null,
      // quick-kayinleong-013 — every location tx (item AND group branches)
      // carries the new location value so the derived "current location" can
      // be read back from the transaction stream. Stored verbatim (Zod already
      // constrains it to a string; "" represents a cleared location).
      location,
    };
  }

  // Step 1: Try SKU / doc ID direct read (O(1) — SKU === doc ID per PROJECT.md)
  const itemSnap = await adminDb.collection("inventory").doc(barcodeValue).get();
  if (itemSnap.exists) {
    const data = itemSnap.data()!;
    const batch = adminDb.batch();
    batch.update(adminDb.collection("inventory").doc(barcodeValue), {
      location,
      updatedAt: FieldValue.serverTimestamp(),
      updatedBy: session.uid,
    });
    batch.set(adminDb.collection("transactions").doc(), {
      ...locationTxFields(),
      itemId: barcodeValue,
      itemSku: (data.sku as string) ?? barcodeValue,
      itemName: (data.name as string) ?? barcodeValue,
      eventId: null,
      eventName: null,
      deliveryOrderId: null,
    });
    await batch.commit();
    revalidatePath("/inventory");
    revalidatePath(`/inventory/${barcodeValue}`);
    return { ok: true, updatedItemIds: [barcodeValue], resolvedAs: "item" };
  }

  // Step 2: Try externalBarcode field match
  const extSnap = await adminDb
    .collection("inventory")
    .where("externalBarcode", "==", barcodeValue)
    .limit(1)
    .get();
  if (!extSnap.empty) {
    const doc = extSnap.docs[0];
    const data = doc.data();
    const batch = adminDb.batch();
    batch.update(adminDb.collection("inventory").doc(doc.id), {
      location,
      updatedAt: FieldValue.serverTimestamp(),
      updatedBy: session.uid,
    });
    batch.set(adminDb.collection("transactions").doc(), {
      ...locationTxFields(),
      itemId: doc.id,
      itemSku: (data.sku as string) ?? doc.id,
      itemName: (data.name as string) ?? doc.id,
      eventId: null,
      eventName: null,
      deliveryOrderId: null,
    });
    await batch.commit();
    revalidatePath("/inventory");
    revalidatePath(`/inventory/${doc.id}`);
    return { ok: true, updatedItemIds: [doc.id], resolvedAs: "item" };
  }

  // Step 3: Try checkoutGroups doc ID
  const groupSnap = await adminDb
    .collection("checkoutGroups")
    .doc(barcodeValue)
    .get();
  if (groupSnap.exists) {
    const group = groupSnap.data() as {
      eventId?: string;
      itemLines?: { itemId: string; itemSku?: string; itemName?: string }[];
    };
    // Unique itemId → { sku, name } from the group's line snapshot, so each
    // location transaction carries the item identity for the history feeds.
    const itemMeta = new Map<string, { sku: string; name: string }>();
    for (const l of group.itemLines ?? []) {
      if (!itemMeta.has(l.itemId)) {
        itemMeta.set(l.itemId, {
          sku: l.itemSku ?? l.itemId,
          name: l.itemName ?? l.itemId,
        });
      }
    }
    const itemIds = [...itemMeta.keys()];
    if (itemIds.length === 0) {
      return { ok: false, error: "Group has no items." };
    }

    // Best-effort event + DO attribution so the move shows in Event and DO
    // history. A lookup miss leaves the field null — it never blocks the
    // location update itself.
    const eventId = group.eventId ?? null;
    let eventName: string | null = null;
    let deliveryOrderId: string | null = null;
    try {
      if (eventId) {
        const evSnap = await adminDb.collection("events").doc(eventId).get();
        eventName = (evSnap.data()?.name as string) ?? null;
      }
      const doSnap = await adminDb
        .collection("deliveryOrders")
        .where("checkoutGroupIds", "array-contains", barcodeValue)
        .limit(1)
        .get();
      if (!doSnap.empty) deliveryOrderId = doSnap.docs[0].id;
    } catch (err) {
      console.error(
        "[updateItemsLocationAction] event/DO attribution failed:",
        err,
      );
    }

    // quick-kayinleong-013/015 — GROUP scans never touch each item's home
    // `inventory.location`. The current location is a property of THIS group
    // (a physical bundle), stored on the checkoutGroups doc — quick-015. A SKU
    // can be split across multiple groups, so writing per-SKU would bleed one
    // group's location across every group sharing that SKU.
    // Per-member location txs are still written (history feeds). The group-doc
    // update + all member txs commit in a single atomic batch.
    const batch = adminDb.batch();
    batch.update(adminDb.collection("checkoutGroups").doc(barcodeValue), {
      location,
    });
    for (const itemId of itemIds) {
      const meta = itemMeta.get(itemId)!;
      batch.set(adminDb.collection("transactions").doc(), {
        ...locationTxFields(),
        itemId,
        itemSku: meta.sku,
        itemName: meta.name,
        eventId,
        eventName,
        deliveryOrderId,
      });
    }
    await batch.commit();
    // The DO detail page reads each group's location server-side, so revalidate
    // the delivery-orders surfaces. The inventory list/detail show the home
    // location (unchanged by a group scan), and the Event tab is a live client
    // subscription — neither needs revalidation here.
    revalidatePath("/delivery-orders");
    if (deliveryOrderId) {
      revalidatePath(`/delivery-orders/${deliveryOrderId}`);
    }
    return { ok: true, updatedItemIds: itemIds, resolvedAs: "group" };
  }

  // T-007-04 — same message for all non-match cases (no information disclosure)
  return { ok: false, error: "Barcode not recognised." };
}

// quick-kayinleong-012 — read-only preview resolver for Scan → Location.
//
// The Location panel previously probed `checkoutGroups` with the client Web
// SDK, which is denied unless the *deployed* Firestore rules grant the read —
// and is also subject to a client-auth-readiness race. Resolving here (Admin
// SDK, server session) makes the preview work regardless of deployed-rule
// state or auth timing, mirroring updateItemsLocationAction's resolution order
// without writing anything.
export async function resolveLocationBarcodeAction(
  barcodeValue: unknown,
): Promise<ResolveLocationBarcodeResult> {
  await requireSession();
  const trimmed = typeof barcodeValue === "string" ? barcodeValue.trim() : "";
  if (!trimmed) return { ok: false };

  // Step 1: SKU / doc ID direct read.
  const itemSnap = await adminDb.collection("inventory").doc(trimmed).get();
  if (itemSnap.exists) {
    const d = itemSnap.data()!;
    return {
      ok: true,
      resolvedAs: "item",
      items: [
        {
          id: trimmed,
          name: (d.name as string) ?? trimmed,
          sku: (d.sku as string) ?? trimmed,
          qty: 1,
        },
      ],
    };
  }

  // Step 2: externalBarcode field match.
  const extSnap = await adminDb
    .collection("inventory")
    .where("externalBarcode", "==", trimmed)
    .limit(1)
    .get();
  if (!extSnap.empty) {
    const doc = extSnap.docs[0];
    const d = doc.data();
    return {
      ok: true,
      resolvedAs: "item",
      items: [
        {
          id: doc.id,
          name: (d.name as string) ?? doc.id,
          sku: (d.sku as string) ?? doc.id,
          qty: 1,
        },
      ],
    };
  }

  // Step 3: checkoutGroups doc ID — recognised even if itemLines is empty
  // (updateItemsLocationAction expands the group authoritatively at submit).
  const groupSnap = await adminDb
    .collection("checkoutGroups")
    .doc(trimmed)
    .get();
  if (groupSnap.exists) {
    const lines =
      (groupSnap.data()!.itemLines as
        | { itemId: string; itemSku?: string; itemName?: string; qty?: number }[]
        | undefined) ?? [];
    // quick-kayinleong-014 — sum qty per itemId so the preview reflects the
    // group's total units (e.g. SHURE-001 × 5), not just the distinct-SKU count.
    const byId = new Map<string, ResolveLocationBarcodeItem>();
    for (const l of lines) {
      const existing = byId.get(l.itemId);
      if (existing) {
        existing.qty += l.qty ?? 0;
        continue;
      }
      byId.set(l.itemId, {
        id: l.itemId,
        name: l.itemName ?? l.itemId,
        sku: l.itemSku ?? l.itemId,
        qty: l.qty ?? 0,
      });
    }
    return { ok: true, resolvedAs: "group", items: [...byId.values()] };
  }

  return { ok: false };
}
